[versions]
foundation = "1.4.0"

[libraries]
applikation-runtime = { module = "tz.co.asoft:applikation-runtime", version.ref = "foundation" }

[plugins]
applikation-plug = { id = "tz.co.asoft.applikation", version.ref = "foundation" }