name: Build & Test

on:
  pull_request:
    branches: [ master ]

env:
  ASOFT_MAVEN_PGP_PRIVATE_KEY: ${{ secrets.ASOFT_MAVEN_PGP_PRIVATE_KEY }}
  ASOFT_MAVEN_PGP_PASSWORD: ${{ secrets.ASOFT_MAVEN_PGP_PASSWORD }}
  ASOFT_NEXUS_PASSWORD: ${{ secrets.ASOFT_NEXUS_PASSWORD }}
  ASOFT_NEXUS_USERNAME: ${{ secrets.ASOFT_NEXUS_USERNAME }}

jobs:
  CD:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/gradle-wrapper.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
          key: ${{ runner.os }}-konan-
          restore-keys: ${{ runner.os }}-konan-

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: 'build/js'
          key: node-modules

      - name: Building plugins
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: ./foundation-plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./foundation-runtimes

      - name: test jvm runtimes
        run: ./gradlew jvmTest
        working-directory: ./foundation-runtimes

      - name: test js node runtimes
        run: ./gradlew jsNodeTest
        working-directory: ./foundation-runtimes

      - name: Building runtimes
        run: ./gradlew build
        working-directory: ./foundation-runtimes

      #      - name: Building samples
      #        run: |
      #          chmod +x ./gradlew
      #          ./gradlew build
      #        working-directory: ./foundation-samples

      - name: Publish & Release Runtimes
        run: ./gradlew publishToSonatype closeAndReleaseStagingRepository
        working-directory: ./foundation-runtimes

      - name: Publishing plugins to sonatype
        run: ./gradlew publishToSonatype closeAndReleaseStagingRepository
        working-directory: ./foundation-plugins

      - name: Publishing plugins to gradle plugin portal
        run: ./gradlew :publishPlugins -Dgradle.publish.key=${{ secrets.ASOFT_GRADLE_PLUGIN_PORTAL_KEY }} -Dgradle.publish.secret=${{ secrets.ASOFT_GRADLE_PLUGIN_PORTAL_SECRET }}
        working-directory: ./foundation-plugins
